---
title: "Operation Data Calculation Test"
format: html
---

## Initializing

```{r}
graphics.off()
rm(list = ls())
gc()

```

## Loading Library

```{r}
library(tidyverse)
library(data.table)
library(lubridate)
library(gt)
library(magrittr)

```

## Import PEP_FUNC

```{r}
source('./pep_func.R')
```


## Loading Data

```{r}
df <- fread('./sample_data.csv')

head(df)
```

```{r}
colnames(df) <- c("time","dwatt","thn",
                  "hpip1","hpip2","hpip3","hpip4",
                  "fsp1","fsp2",
                  "cv_pos1","cv_pos2","cv_pos3","cv_pos4",
                  "vent_vv","cv_inner_temp","cv_outer_temp",
                  "lpa_bp1","lpa_bp2","lpa_bp3")
```

```{r}
df$time <- as.POSIXct(df$time, format = "%Y-%m-%d %H:%M")

```

```{r}
str(df)

```

```{r}
df %<>% mutate(h_test = stmPTH(fsp1, cv_inner_temp), .after = 8)

```


```{r}
# section efficiency test
p1 <- 255.0 #bara
h1 <- 3381.6 #kJ/kg
p2 <- 59.82 #bara
h2 <- 3018.9 #kJ/kg

hp_eff <- section_eff(p1, h1, p2, h2, 1)

hp_eff # excel pep_func result = 0.893039

```

```{r}
# Temperature calculation test
t1 <- stmPHT(p1, h1)

t1 # 565C

```

```{r}
# Calculate mean and standard deviation of the data
mean_val <- mean(df$dwatt)
sd_val <- sd(df$dwatt)

# Create scatter plot with standard deviation, min, and max values as annotations
ggplot(df, aes(x = 1:length(dwatt), y = dwatt)) +
  geom_point(alpha = 0.5) +
  geom_hline(yintercept = mean_val, linetype = "dashed", color = "red") +
  geom_hline(yintercept = mean_val + sd_val, linetype = "dashed", color = "blue") +
  geom_hline(yintercept = mean_val - sd_val, linetype = "dashed", color = "blue") +
  annotate("text", x = 1, y = max(df$dwatt), label = paste("Max =", max(df$dwatt)), color = "darkgreen", hjust = 0) +
  annotate("text", x = 1, y = min(df$dwatt), label = paste("Min =", min(df$dwatt)), color = "darkgreen", hjust = 0) +
  annotate("text", x = 1, y = mean_val + sd_val + 1, label = paste("SD =", round(sd_val, 2)), color = "blue", hjust = 0, vjust = -0.4) +
  labs(x = "Index", y = "dwatt", title = "Scatter Plot of dwatt") +
  theme_minimal()

```

